### ISSUE TITLE
printout of namelist in *.ps files

### ISSUE THREAD

**Issue by ypetrov** [garrettwrong/cql3d_f90#30]
The initial part of cqlinput namelist is not printed into *.ps file. Probably the issue is related to ainplt.f90, this line:
1    continue   ! loop in reading lines in cqlinput file
For some reason, now the cqlinput content is printed starting from &trsetup group, rather than from &setup0 group.  So it means that when the code gets to that line in subr. ainplt, the "cursor" is not at beginning of the list (cqlinput file).

**Comment by garrettwrong** [comment]
I can take a look.  I'm not sure exactly I understand the problem.

You were printing the namelist into the PS, and now setup0 is missing?  That would probably make sense given the change from yesterday.

**Comment by ypetrov** [comment]
&setup0 and &setup are missing. The printout starts from the &trsetup list.


Quoting Garrett Wright <notifications@github.com>:

**Comment by ypetrov** [comment]
Looks all good.  I will do more tests on my PC.
